apiVersion: v1
kind: Service
metadata:
  name: fusionauth-search
  namespace: default
spec:
  ports:
  - name: http
    port: 9200
  selector:
    app: fusionauth-search
---
apiVersion: v1
kind: Service
metadata:
  name: fusionauth-search-discovery
  namespace: default
spec:
  selector:
    app: fusionauth-search
  ports:
    - name: transport
      port: 9300
      protocol: TCP
  clusterIP: None